

- name: clean user
  shell: mv  /var/run/utmp /var/run/utmp_; touch  /var/run/utmp;
  sudo: yes

- name: remove user
  user: name={{username}} state=absent remove=yes force=yes
  sudo: yes
  
- name: remove user default home
  file: path=/home/{{username}}  state=absent
  sudo: yes

- name: remove user home
  file: path=/opt/{{username}}  state=absent
  sudo: yes

- name: remove group
  group: name={{username}} state=absent
  sudo: yes
  
- name: create group
  group: name={{username}} state=present gid=2000
  sudo: yes
  
- name: create user
  user: name={{username}} password={{common.crypt_passwd}} group={{username}} uid=2000 createhome=yes
  sudo: yes

- name: create home dir
  sudo: yes
  file: path=/opt/{{username}} state=directory owner={{username}} group={{username}} mode=700 

