
- name: Check whether the disk is mounted
  shell: df -h|grep /opt |wc -l
  sudo: yes
  register: is_partitioned
  
- name: init system user
  include: init_disk.yml
  when: ( is_check_installed is not defined or "{{is_partitioned.stdout}}" == "0" )