### check cpu ###
- name: get cpu result
  shell: grep -c '^processor' /proc/cpuinfo
  register: cpu_result
  sudo: yes

### check memory ###
- name: get memory result
  shell: awk '/MemTotal/{print $2/1000/1000}' /proc/meminfo
  register: mem_result
  sudo: yes
