### check disk ###
- name: get /opt disk volume
  shell: df -k|awk '$1~/\dev\/[a-z][a-z][a-z]?[b-z][1-9]/&&$6~/\/opt$/{print $4/1024/1024}'
  register: opt_disk_volume
  sudo: yes

- name: get /opt disk volume Use%
  shell: df -h|awk '$1~/\dev\/[a-z][a-z][a-z]?[b-z][1-9]/&&$6~/\/opt$/{print substr($5,0,length($5)-1)}'
  register: opt_disk_volume_use

- name: get /var/log disk volume
  shell: df -k|awk '$1~/\dev\/[a-z][a-z][a-z]?[b-z][1-9]/&&$6~/\/var\/log$/||$6~/\/var\/log\/apigateway$/||$6~/\/var\/log\/console/{print $4/1024/1024}'
  register: var_log_apigateway_disk_volume
  sudo: yes  

- name: get /var/log disk volume Use%
  shell: df -h|awk '$1~/\dev\/[a-z][a-z][a-z]?[b-z][1-9]/&&$6~/\/var\/log$/||$6~/\/var\/log\/apigateway$/||$6~/\/var\/log\/console/{print substr($5,0,length($5)-1)}'
  register: var_log_apigateway_disk_volume_use
  sudo: yes
