---
- name: add sudo no password permission
  lineinfile: dest={{common.etc_sudoer_path}} regexp='^{{common.user_apigateway}} ALL=NOPASSWD:ALL' line='{{common.user_apigateway}} ALL=NOPASSWD:ALL'
  sudo: yes
  tags:
    -  cassandra_uninstall  
 
- stat: path={{cassandra.path}}/install
  register: p 
  tags:
    - cassandra_uninstall
    - stop_cassandra
    
- name: stop crontab
  shell: service cron stop
  when:  p.stat.isdir is defined and p.stat.isdir  
  sudo: yes 
  tags:
    - stop_cassandra    
    
- name: stop
  shell: sh {{cassandra.bin_dir}}/monitor_cassandra.sh stop
  when:  p.stat.isdir is defined and p.stat.isdir
  ignore_errors: true
  tags:
    - cassandra_uninstall  
    - stop_cassandra

- name: uninstall cassandra
  shell: sh {{cassandra.path}}/install/cassandra_uninstall.sh
  when:  p.stat.isdir is defined and p.stat.isdir
  ignore_errors: true
  tags:
    - cassandra_uninstall
    
- name: create log dir
  sudo: yes
  file: path={{common.apigateway_log}} state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}}

- name: upload cassandra package
  copy: src={{cassandra.pkg_dir}}/{{cassandra.pkg_name}}  dest={{cassandra.home}} force=yes
  
- name: untar cassandra
  unarchive: src={{cassandra.home}}/{{cassandra.pkg_name}}  dest={{cassandra.home}} copy=no

- name: config cassandra ip
  lineinfile: dest={{cassandra.install_config_file}} regexp='^LOCAL_IP=' line='LOCAL_IP={{ansible_ssh_host}}'

- name: dos2unix trans install script
  shell: dos2unix {{cassandra.path}}/install/*

- name: dos2unix trans bin script
  shell: dos2unix {{cassandra.bin_dir}}/*

- name: install cassandra
  shell: sh cassandra_install.sh
  args:
    chdir: '{{cassandra.path}}/install'
    
- name: config cassandra.yaml
  template: src=cassandra.yaml dest=/opt/{{common.user_apigateway}}/cassandra/conf mode=0600 owner={{common.user_apigateway}} group={{common.user_apigateway}}    

- name: delete sudo NOPASSWORD 
  shell: sed -i "/{{common.user_apigateway}} ALL=NOPASSWD:ALL/d" {{common.etc_sudoer_path}}
  sudo: yes
  tags:
    - cassandra_uninstall
  
- name: remove source tar
  file: path={{common.home_dir}}/{{cassandra.pkg_name}} state=absent    

- name: start
  shell: sh monitor_cassandra.sh restart
  args:
    chdir: '{{cassandra.bin_dir}}'
  tags:
    - cassandra_restart  