---
- stat: path={{silvan.bin_dir}}
  register: p

- name: install component
  include: ./install_silvan.yml
  when:  ( is_check_installed is not defined or ('{{is_check_installed|default(false)}}'== true and p.stat.islnk is not defined))
