# check is installed java
- name: check the jdk version
  shell: source /etc/profile; java -version 2>&1 >/dev/null | grep 'java version' | awk '{print $3}'
  register: jdk_exist
  tags:
    - jdk_uninstall
    - install_jdk   
  
- name: install component
  include: ./install_jdk.yml 
  when:  ( is_check_installed is not defined or '{{jdk_exist.stdout|default()}}'=='')
