---
- stat: path={{nginx.bin_dir}}
  register: p_check
  sudo: yes

- name: install component
  include: install_nginx.yml
  when:  ( (is_check_installed is not defined) or (p_check.stat is not defined) or (p_check.stat.exists == false) )   
