
- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False
  roles:
    - backup_shubao

- hosts: asgard
  gather_facts: False 
  roles:
    - backup_asgard
    
- hosts: cassandra
  gather_facts: False 
  roles:
    - backup_etl    

- hosts: silvan
  gather_facts: False  
  roles:
    - backup_silvan 
  tags:
    - backup_silvan     

- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  gather_facts: False  
  roles:
    - backup_nginx     