---

- hosts: memcached
  gather_facts: False
  roles:
    - jdk
    - memcached
    - dns
    - ntp
    - common
  tags:
    - memcached

- hosts: kafka
  gather_facts: False
  roles:
    - get_zk_ip_addr
  tags:
    - get_zk_ip_addr

- hosts: kafka
  gather_facts: False
  roles:
    - zookeeper
  tags:
    - zookeeper

- hosts: kafka
  gather_facts: False
  roles:
    - jdk
    - kafka
    - dns
    - ntp
    - common
  tags:
    - kafka

- hosts: kafka
  gather_facts: False
  roles:
    - jdk
    - zookeeper
    - kafka
    - dns
    - ntp
    - common
  tags:
    - zk_kfk

- hosts: cassandra
  gather_facts: False
  roles:
    - jdk
    - cassandra
    - etl
    - { role: cassandra_init, when: "INIT_NODE == 'Y'" }
    - dns
    - ntp
    - common
  tags:
    - cassandra

- hosts: asgard
  gather_facts: False
  roles:
    - jdk
    - asgard
    - dns
    - ntp
    - common
  tags:
    - asgard

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False
  roles:
    - shubao_go
    - dns
    - ntp
    - common
  tags:
    - shubao

- hosts: silvan
  gather_facts: False
  roles:
    - jdk
    - silvan
    - dns
    - ntp
    - common
  tags:
    - silvan

- hosts: silvan
  gather_facts: False
  roles:
    - config_gaussdb_backup
  tags:
    - config_db_backup

- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  gather_facts: False
  roles:
    - jdk
    - nginx
    - dns
    - ntp
    - common
  tags:
    - nginx

- hosts: shubao_nginx;shubao_pod_nginx;silvan_nginx
  gather_facts: False
  roles:
    - ha
  tags:
    - ha_nginx

- hosts: all
  gather_facts: False
  roles:
    - health_check
  tags:
    - health_check

- hosts: all
  gather_facts: False
  roles:
    - base_check
  tags:
    - base_check

- hosts: all
  gather_facts: False
  roles:
    - cancel_root
  tags:
    - cancel_root

- hosts: all
  gather_facts: False
  roles:
    - before_deploy
  tags:
    - before_deploy

- hosts: all
  gather_facts: False
  roles:
    - elk
  tags:
    - elk

- hosts: all
  gather_facts: False
  roles:
    - jdk
    - dns
    - ntp
    - common
  tags:
    - common_install

- hosts: all
  gather_facts: False
  roles:
    - dns
    - ntp
    - common
  tags:
    - common

- hosts: all
  gather_facts: False
  roles:
    - dns
  tags:
    - dns

- hosts: all
  gather_facts: False
  roles:
    - ntp
  tags:
    - ntp

- hosts: all
  gather_facts: False
  roles:
    - initsystem
    - initsysuser
  tags:
    - init_sys

- hosts: all
  gather_facts: False
  roles:
    - initsysuser
  tags:
    - initsysuser

- hosts: all
  gather_facts: False
  roles:
    - initsystem
  tags:
    - init_disk

- hosts: all
  gather_facts: False
  roles:
    - common_clean
  tags:
    - common_clean

- hosts: all
  gather_facts: False
  roles:
    - common_clean
  tags:
    - post_common_clean

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
    - check_var
  tags:
    - check_var


- hosts: all
  gather_facts: False
  roles:
    - common

- hosts: all
  gather_facts: False
  roles:
    - common
  tags:
    - post_common

- hosts: all
  gather_facts: False
  roles:
    - common_clean
  tags:
    - upgrade_common_clean

- hosts: [shubao_public,shubao_pod,shubao_tsz,asgard,silvan]
  gather_facts: False
  roles:
    - omm
  tags:
    - omm

- hosts: shubao_nginx;shubao_pod_nginx;silvan_nginx
  gather_facts: False
  roles:
    - ha_upgrade
  tags:
    - upgrade_ha
