---

- hosts: all
  gather_facts: False
  roles:
    - jdk
  tags:
    - jdk

- hosts: memcached
  gather_facts: False
  roles:
    - memcached
  tags:
    - memcached

- hosts: kafka
  gather_facts: False
  roles:
    - zookeeper
    - kafka
  tags:
    - mq

- hosts: asgard
  gather_facts: False
  roles:
    - asgard
  tags:
    - asgard

- hosts: shubao_public;shubao_pod;shubao_tsz
  gather_facts: False
  roles:
    - shubao_go
  tags:
    - shubao_go

- hosts: shubao_nginx;shubao_pod_nginx;silvan_nginx
  roles:
    - nginx
  tags:
    - nginx

- hosts: all
  gather_facts: False
  roles:
    - dns
    - ntp
    - common
    - common_clean
  tags:
    - common
