---
- hosts: memcached
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk

- hosts: kafka
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk

- hosts: asgard
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk

- hosts: silvan
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk

- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  serial: 1
  roles:
    - initsystem
  tags:
    - mount_disk
