- hosts: memcached
  gather_facts: False   
  roles:
    - jdk
    - health_check    
  tags:
    - jdk_upgrade
    
- hosts: silvan
  gather_facts: False 
  serial: 1
  roles:
    - jdk
    - silvan
    - health_check    
  tags:
    - jdk_upgrade    
    
- hosts: asgard
  gather_facts: False    
  roles:
    - jdk
    - asgard
    - health_check
  tags:
    - jdk_upgrade
   
- hosts: kafka
  serial: 1  
  gather_facts: False 
  roles:
    - jdk
    - zookeeper
    - kafka
    - health_check    
  tags:
    - jdk_upgrade
 
- hosts: cassandra
  gather_facts: False 
  serial: 1
  roles:
    - jdk
    - cassandra
    - health_check    
  tags:
    - jdk_upgrade    
    
- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False 
  serial: 1
  roles:
    - jdk
    - health_check    
  tags:
    - jdk_upgrade
    
- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  gather_facts: False   
  serial: 1
  roles:
    - jdk
    - nginx
  tags:
    - jdk_upgrade    