         
- hosts: asgard
  serial: 1
  roles:
    - oc_asgard
    - asgard
    - health_check

- hosts: silvan
  serial: 1
  roles:
    - oc_silvan
    - silvan
    - health_check
    
- hosts: shubao
  serial: 1
  roles:
    - oc_shubao_go
    - shubao_go
    - health_check
