
- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  serial: 1
  roles:
    - restore_nginx
  tags:
    - restore_nginx

- hosts: silvan
  serial: 1
  roles:
    - restore_silvan
    - health_check     
  tags:
    - restore_silvan

- hosts: asgard
  serial: 1
  roles:
    - restore_asgard
    - health_check
  tags:
    - restore_asgard

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  serial: 1
  roles:
    - restore_shubao
    - health_check
  tags:
    - restore_shubao
