---

- hosts: silvan
  gather_facts: False
  roles:
    - silvan
  tags:
    - silvan

- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  gather_facts: False
  roles:
    - nginx
    - ha
  tags:
    - nginx

- hosts: memcached
  gather_facts: False
  roles:
    - memcached
  tags:
    - memcached

- hosts: kafka
  gather_facts: False
  roles:
    - zookeeper
    - kafka
  tags:
    - mq

- hosts: cassandra
  gather_facts: False
  roles:
    - cassandra
    - etl
    - { role: cassandra_init, when: "INIT_NODE == 'Y'" }

- hosts: asgard
  gather_facts: False
  roles:
    - asgard
  tags:
    - asgard

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False
  roles:
    - shubao_go
  tags:
    - shubao_go
