- hosts: memcached
  roles:
    - memcached
    
- hosts: asgard
  roles:
    - asgard
 
- hosts: [shubao_public,shubao_pod,shubao_tsz]
  roles:
    - shubao_go
    
- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  roles:
    - ha_stop
    
- hosts: kafka
  roles:
    - kafka    
    - zookeeper
    