---

- hosts: silvan;asgard;shubao_public;shubao_pod;shubao_tsz
  roles:
    - omm

- hosts: memcached
  roles:
    - memcached

- hosts: shubao_nginx;shubao_pod_nginx;silvan_nginx
  roles:
    - nginx
    - ha

- hosts: silvan
  roles:
    - silvan


- hosts: asgard
  roles:
    - asgard


- hosts: cassandra
  roles:
    - cassandra
    - etl

- hosts: kafka
  roles:
    - kafka
    - zookeeper

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  roles:
    - apigateway
    - tomcat
    - shubao_go


- hosts: all
  roles:
    - jdk
    - cancel_root
    - common_clean

