
- hosts: memcached
  gather_facts: False
  roles:
    - memcached
  tags:
    - memcached_upgrade

- hosts: kafka
  gather_facts: False
  roles:
    - kafka

- hosts: silvan
  gather_facts: False
  serial: 1
  roles:
    - silvan
  tags:
    - silvan_upgrade

- hosts: asgard
  gather_facts: False
  roles:
    - asgard
  tags:
    - asgard_upgrade

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False
  serial: 2
  roles:
    - apigateway
    - tomcat

- hosts: [shubao_public,shubao_pod,shubao_tsz]
  gather_facts: False
  serial: 2
  roles:
    - shubao_go
  tags:
    - shubao_upgrade

- hosts: cassandra
  gather_facts: False
  roles:
    - etl
  tags:
    - cassandra_upgrade

- hosts: [shubao_nginx,shubao_pod_nginx,silvan_nginx]
  gather_facts: False
  serial: 1
  roles:
    - nginx

- hosts: all
  gather_facts: False
  roles:
    - health_check
