- stat: path={{apigateway.script_home}}/conf
  register: p_check 
 
- name: install component
  include: install_shubao.yml
  when:  ( (is_check_installed is not defined) or (p_check.stat is not defined) or (p_check.stat.exists == false) ) 
